- hosts: jumpbox
  tasks:
   - name: Fetch Instance Info
     os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
     register: result
   - name: Terminate servers 
     os_server:
      state: absent
      name: "{{ item.name }}"
      delete_fip: true
     with_items: "{{ result.ansible_facts.openstack_servers }}"
